// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnewniipdwtloqqyzqni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZXduaWlwZHd0bG9xcXl6cW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjM4NTEsImV4cCI6MjA3MjkzOTg1MX0.kGL6ZUceZdc2oO8hSUgUxEkQbwHmfruNa3BPkF56r08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});